$(document).ready(function(){
  console.log("ready")
  $('#button-default-theme').click(function(){
    $("body").removeClass();
    $("body").addClass("body-default-theme");
    $("#intro").removeClass();
    $("#intro").addClass("intro-default-theme");
  });
  $('#button-dark-theme').click(function(){
    $("body").removeClass();
    $("body").addClass("body-dark-theme");
    $("#intro").removeClass();
    $("#intro").addClass("intro-dark-theme");
  });
});
